config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'projects#index'

  resources :tasks
  resources :projects
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Task, user_id: user.id
    can :manage, Project, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_paranoid
  
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  acts_as_paranoid
  
  belongs_to :project
  belongs_to :user

  validates :name, presence: true
  validates :priority, inclusion: 1..10

  scope :finished, -> { where(is_done: true) }
  scope :pending, -> { where(is_done: false) }

  def done?
    is_done
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :projects, dependent: :destroy
  has_many :tasks, dependent: :destroy

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @projects = @projects.includes(:tasks)
  end

  def show; end

  def new; end

  def edit; end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to root_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to root_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def task_params
      params.require(:task).permit(:name, :is_done, :priority, :due_on, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GarageTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container-fluid'>
      <div class='container'>
        <%= yield %>
      </div>
    </div>

    <div class='clearfix'></div>
    <br>
    <div class='text-center'>
      <% if @current_user %>
        <%= link_to "<i class='fa fa-sign-out' aria-hidden='true'></i> Sign Out".html_safe, destroy_user_session_path, method: :delete %>
      <% end %>
      <p id='copy'>&copy; Ruby Garage</p>
      <br>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, remote: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="form-group">
      <%= form.label 'TODO List Name' %>
      <%= form.text_field :name, class: 'form-control', required: true %>
    </div>

    <%= form.submit nil, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice text-center"><%= notice %></p>

<div class='title-block'>
  <h1 class="main-title">Simple todo list</h1>
  <h3 class="secondary-title">from ruby garage</h3>
</div>

<br>

<div class='project-list'>
  <% @projects.each do |project| %>

    <div class="card">
      <div class="project-header">
          <div class="calendar-icon"><i class="fa fa-calendar"></i></div>
          <div class="project-name"><p><%= project.name %></p></div>
          <div class="remove-icon"><%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, project_path(project), method: :delete, data: { confirm: 'Confirm?' } %></div>
          <div class="edit-icon"><%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_project_path(project) %></div>
      </div>
      <div class="new-task">
        <div class="custom-file">
          <i class="fa fa-plus green-plus"></i>
          <%= form_with model: project.tasks.build, remote: true do |f| %>
            <%= f.submit 'Add Task', class: 'btn btn-success task-button' %>
            <%= f.text_field :name, class: 'form-control task-field', required: true %>
            <%= f.hidden_field :project_id, value: project.id %>
          <% end %>
        </div>
      </DIV>
      <div class="card-body">
        <table class='table table-bordered'>
          <% project.tasks.order(:is_done).each do |task| %>
            <% next if task.new_record? %>
            <tr>
              <td width="50">
                <%= link_to "<input type='checkbox' #{task.is_done ? 'checked' : ''}>".html_safe, task_path(task, "task[is_done]": !task.is_done), method: :patch, remote: true %>
              </td>
              <td class="<%= "done-#{task.is_done}" %>"><%= task.name %></td>
              <td width="115">
                <% unless task.is_done %>
                  <div class="remove-icon"><%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, task_path(task), method: :delete, data: { confirm: 'Confirm?' } %></div>
                  <div class="edit-icon"><%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_task_path(task) %></div>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>

    <br>

  <% end %>
</div>

<br>

<div class='button-block'>
  <%= link_to '<i class="fa fa-plus plus"></i> Add TODO List'.html_safe, new_project_path, class: 'btn-custom' %>

</div>

app/views/projects/new.html.erb
<section class='content'>

  <h1>New TODO List</h1>

  <%= render 'form', project: @project %>

  <br>

  <%= link_to 'Back', projects_path %>

</section>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="form-group">
      <%= form.label 'Task name' %>
      <%= form.text_field :name, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= form.label 'Priority' %>
      <%= form.number_field :priority, in: 1..10, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label 'Due on' %>
      <%= form.date_field :due_on, class: 'form-control' %>
    </div>

    <%= form.submit nil, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>